services:

  backend:
    build: .
    ports:
      - "5114:8080"

    depends_on:
      - redis

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RedisConnection=redis:6379

  redis:
    image: redis:7-alpine

    ports:
      - "6379:6379"

  mysql:
    image: mysql:8.0

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: pokerdb

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: